### ISSUE TITLE
Duplicated removal of skills in Archetypes

### ISSUE THREAD

**Issue by pikachu01** [JohN100x1/IsekaiMod#145]
**Describe the bug**
Not sure if its intended that some removal/additions are overlapping. Some might be intentional (2 Beach Episodes, and 1 being removed?), but I'm pasting all the ones that seems suspicious.

**To Reproduce**
1. Create a new character and view the details

**Expected behavior**
Expected behaviour is that some skills that are clearly removed aren't readded again (unless it is intentional)

**Screenshots**
![image](https://user-images.githubusercontent.com/1090194/233667440-54f189fb-d18e-46c5-9c6a-9efc6ce38d36.png)
![image](https://user-images.githubusercontent.com/1090194/233667669-fd0dc157-283a-45c3-b78f-948a6e517d11.png)
![image](https://user-images.githubusercontent.com/1090194/233667744-f63f6b99-ae4a-4bf2-938f-643d62f4cb97.png)
![image](https://user-images.githubusercontent.com/1090194/233667861-3c75d725-c430-4e1e-8e80-3794add3ad53.png)
![image](https://user-images.githubusercontent.com/1090194/233667927-3f7bfd3b-1901-4ecb-a87b-4558be22ed3a.png)
![image](https://user-images.githubusercontent.com/1090194/233668067-1693c5de-f4f6-494c-a2e2-fa3268dcd4f1.png)
![image](https://user-images.githubusercontent.com/1090194/233668140-0fc2de12-b33f-4c10-a69c-cc933b78835c.png)
![image](https://user-images.githubusercontent.com/1090194/233668188-fab21217-8181-42ff-8a8d-d2e24f9a8905.png)
![image](https://user-images.githubusercontent.com/1090194/233668619-98f6c287-031a-4677-b698-047d23820cde.png)
![image](https://user-images.githubusercontent.com/1090194/233668670-6024fc62-e89b-45d5-b36f-8e1db3ff6b15.png)

**Additional context**
N/A

**Comment by JohN100x1** [comment]
It's intended that the base class has double selections, so what is being removed is not the same feature. I will proabably change the name to `Extra Beach Episode` in the next update.

**Comment by pikachu01** [comment]
How about Quick Footed?

**Comment by JohN100x1** [comment]
That one is just a replacement to match the casting stat of the subclasses
