### ISSUE TITLE
"Rlease Energy" not granting "Channel positive/negative Energy" ability

### ISSUE THREAD

**Issue by NightOwlByDay** [JohN100x1/IsekaiMod#148]
Upon reaching level 3 and aquiring the "Release Energy" Feature, the Isekai Protagonist does not  gain the channel positive or negative energy ability.

**To Reproduce**
1. Create character with Isekai Protagonist class
2. Level character to at least level 3
3. Check available Abilities above Hotbar

**Expected behavior**
I'm honestly a little unclear on this point. Going by the description I'd assume the character is supposed to gain the ability to channel positive energy and the ability to channel negative energy? Or is this dependent on alignement or something similar?

**Screenshots**
![image](https://user-images.githubusercontent.com/130167830/235375053-fb785d23-ad0b-4508-8226-c919887db9cf.png)
![image](https://user-images.githubusercontent.com/130167830/235375065-a455fbed-d3e6-4876-93ea-3cf94a5368b8.png)

Offtopic:
The 5.0 additions / changes are awesome :D ! I especially like the changes to the base Isekai Protagonist class.

The Fix for the Bloodrager Bloodlines Selection List not being populated works like a charm as well :).

**Comment by JohN100x1** [comment]
This should be fixed now [5.0.4](https://github.com/JohN100x1/IsekaiMod/releases/tag/5.0.4)

**Comment by NightOwlByDay** [comment]
Just got around to playing again. Fix works for new character reaching level 3 and retroactively granting both "channel positive energy" and "channel negative energy" abilities to character with character level greater 3.

Thank you for the quick fix :) !
