### ISSUE TITLE
Weapons that use strength doesn't factor in Charisma replacement

### ISSUE THREAD

**Issue by pikachu01** [JohN100x1/IsekaiMod#155]
**Describe the bug**
Weapons that uses strength for damage doesn't factor in Charisma in Isekai Archetypes that replaces Strength with Charisma for factoring in damage. Example: Composite Longbow/Shortbow/Throwing Axes.

**To Reproduce**
1. Use Composite Bow on a low strength Hero Archetype Isekai character
2. See that the damage is low as it uses Strength rather than Charisma

**Expected behavior**
Charisma should still replace Strength on a Composite Longbow weapon

**Screenshots**
![image](https://user-images.githubusercontent.com/1090194/236501684-147c201d-d1bc-4448-900d-0bf4a6363fdf.png)

**Comment by JohN100x1** [comment]
From what I can see, the composite enchantment and the `Graceful Combat` feature both uses the same `OverrideDamageBonusStat` method to override the weapon stat calculation, and that the composite enchnatment is also applied after the `Graceful Combat` feature, meaning only the composite enchnatment is effective.

Possible solutions:
- Patching the composite enchantment to check for specific hardcoded features like the `Graceful Combat` feature before doing the stat replacement. Repeat for strength weapons, agile weapons, finesse weapons etc.
- Get the `Graceful Combat` feature to trigger last. (no idea how at the moment)
- Do nothing. Let the weapon enchantments take priority in this case.

I will investigate whether the 2nd solution is possible but if not I would rather let the weapon enchantments take priority.

**Comment by NightOwlByDay** [comment]
I'd like to add that I noticed the same behavior with the feature that lets you use Dexterity for damage from the Edge Lord Subclass. "Sonic Strike" was it's name, I think.
On Composite LongBows, characters strength is used for Damage Calculations.
On non Composite Longbows, dexterity was used for damage.

**Comment by JohN100x1** [comment]
I think I will leave it as it is. I couldn't find a way to re-order the weapon stat calculation when multiple sources override the weapon stat.
