### ISSUE TITLE
[5.0.5] "Extra Strike" not giving expected number of extra attacks | Base Isekai Class - Secret Power

### ISSUE THREAD

**Issue by NightOwlByDay** [JohN100x1/IsekaiMod#156]
**Describe the bug**
When selcting "Extra Strike" as the Secret Power of the base Isekai class at level 10, the character only gains one extra attack.

**To Reproduce**
1. Create character with base Isekai class
2. Level character to level 10
3. Pick "Extra Strike" as Secret Power
4. Check character sheet for number of attacks.

**Expected behavior**
As per the description of "Extra Strike" I'd expect, that the character gains two extra attacks at level 10. One from level 5 and one from level 10 , for a total of 4 attacks per round at level 10, two from normal class / BAB progression and two from "Extra Strike". Excluding any buffs like haste etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/130167830/236614926-3fd59946-8f78-45c8-b99e-7dd97eeff5bf.png)

**Comment by JohN100x1** [comment]
I don't intend to give the base class more than one extra attack. I will update the description.
