### ISSUE TITLE
Eldritch Archer magus legacy spell combat not working properly

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/IsekaiMod#164]
> whenever I use a ranged touch spell with my character the attacks don't follow and if I try to use another ranged touch spell on the same turn since the first is auto quickened the spell completely fizzles... Originally I thought it might've been cause of zippy magic (though I am sure eldritch archer used to work with zippy magic before) but even deactivating it or removing it through toybox didn't fix the issue

Solution will require patching the `UnitPartMagus.IsSpellFromMagusSpellList` method to include spells from Isekai protagonist spelllist.

**Comment by SkySkyey** [comment]
Mine is also the same and its just the normal magus class. Whenever i tried using spellstrike with melee touch, it wont do the spell at all, i can't even click anything with touch spell. is there anyway I can fix this?
