### ISSUE TITLE
Adjustable or skip spell selection

### ISSUE THREAD

**Issue by Red-Pill0** [JohN100x1/IsekaiMod#169]
I usually play on controller and respeccing to try new things is a pain cause of the amount of spells you need to pick every time and not to mention putting the 100+ spells on your bar. Also you get less skill bars on controller, not only do you lose 2 bars, but all the bars are also shorter. Is it possible to make the amount of spell picks adjustable? Hell being able to skip spell selections would also work. I've tried to use the skip spell selection option in toybox but for whatever reason it only works on mastermind.

**Comment by JohN100x1** [comment]
I'll add this in the next update

**Comment by Red-Pill0** [comment]
Thank you very much!
