### ISSUE TITLE
Isekai Spellist

### ISSUE THREAD

**Issue by Nerin3** [JohN100x1/IsekaiMod#175]
The automatically generated spell list for Isekai protagonist includes few spells and abilities intended only for cutscenes:
I only found this one, but there might me others:
RayOfEnfeeblmentCutsceneQuickened

**Comment by Nerin3** [comment]
Okay got another spell that got duplicated
You have
BestowGrace and BestowGraceCast

**Comment by JohN100x1** [comment]
Thanks for letting me know. Those spells should be removed now.

**Comment by Nerin3** [comment]
Cure Critical Wounds also appears twice as
selectable spell (haven't checked but probably as CureCriticalWounds and CureCriticalWoundsCast)

**Comment by JohN100x1** [comment]
Cool. I'll work on that now.
