### ISSUE TITLE
Skald Legacy

### ISSUE THREAD

**Issue by Nerin3** [JohN100x1/IsekaiMod#177]
Picking Skald legacy gives you level 0 spellbook for skald.

**Comment by Nerin3** [comment]
Oh and Cure Critical Wounds also appears twice as selectable spell

**Comment by JohN100x1** [comment]
which skald legacy and what level are you?

**Comment by Nerin3** [comment]
I picked it as second part-time legacy and it was metal skald legacy.

**Comment by JohN100x1** [comment]
which rage power and skald talent did you choose?

**Comment by Nerin3** [comment]
It was Last Azlanti save I already lost (I learned the hard way that companion death during their quest also deletes the save)
But it was either lesser demonic totem or lethal stance.
As for talent 99% it was the one that allows you to stand up without provoking attacks of opportunity.

**Comment by JohN100x1** [comment]
I think it might be a feature which references the skald spellbook in one of it's components, but I can't find the feature in the progression which does that. Could you try to reproduce the bug?

**Comment by Nerin3** [comment]
The funny thing is I cannot reproduce it, it's as if only happened in that one instance. I didn't change anything with my mods, but somehow it's working as intended now.

**Comment by Nerin3** [comment]
I will reopen this when I encounter it again.
