### ISSUE TITLE
Correction of the translation.

### ISSUE THREAD

**Issue by Necht** [JohN100x1/IsekaiMod#178]
Hi! I am now free and can devote a lot of time to help with the translation of your mod into russian.
In this regard, I may have several questions about the meaning of certain words or actions. That's why I decided to create this topic where we could discuss it and where you, in case of introducing new skills, could write to me about it so that I would immediately translate.
But first, can you please remind me how I can correct the current translation?

**Comment by JohN100x1** [comment]
You can create a fork of this repository and then edit the [LocalizationPack.json](https://github.com/JohN100x1/IsekaiMod/blob/master/IsekaiMod/Localization/LocalizationPack.json) file. Once you finished making changes, you can create a pull request so I can merge into this repository.

**Comment by Necht** [comment]
Also, while I was doing the translation, I noticed a little oddity. 
There were no lines in the localization file to translate the mod settings menu

![image](https://github.com/JohN100x1/IsekaiMod/assets/128060492/4a325f0b-779b-4b5c-b06e-36d757bd65d7)

![image](https://github.com/JohN100x1/IsekaiMod/assets/128060492/c56a0aff-8721-422d-b5c7-11928089d53d)

![image](https://github.com/JohN100x1/IsekaiMod/assets/128060492/234ca35e-e5b4-434a-9f7d-e5cdb45a985b)

**Comment by Necht** [comment]
And I have a little idea from the changes of some abilities:

Excalibur - сhange into a toggle ability

Exceptional Features - can only be selected if there is an issekai hero level or mythical levels (for companions)

**Comment by JohN100x1** [comment]
> But to be honest, I don't quite understand how to create a pull reques. This is the first time I've done something like this on this site. Can you please explain?

1. First install [git](https://git-scm.com/downloads).
2. Next, create a fork of this repository [here](https://github.com/JohN100x1/IsekaiMod/fork).
3. Now open the terminal on your computer and enter `git clone https://github.com/Necht/IsekaiMod.git`.
4. Replace the `LocalizationPack.json` with your edited version.
5. In the terminal enter `git add .`
6. Then `git commit -m "feat: update russian in LocalizationPack.json"`
7. Then `git push -u origin master`
8. You can create a new pull request [here](https://github.com/JohN100x1/IsekaiMod/pulls) by clicking on the `New pull request` button.

> Also, while I was doing the translation, I noticed a little oddity.
There were no lines in the localization file to translate the mod settings menu

The settings menu doesn't use localized strings. It's hardcoded. The mechanism to change switch between localization in the game doesn't apply to the mod settings menu.

**Comment by JohN100x1** [comment]
If it's easier then you can send me the `LocalizationPack.json` instead, and I can send you the updated `IsekaiMod.zip` file.

**Comment by Necht** [comment]
> If it's easier then you can send me the `LocalizationPack.json` instead, and I can send you the updated `IsekaiMod.zip` file.

I tried to do this, but an error came out:
![image](https://github.com/JohN100x1/IsekaiMod/assets/128060492/7db72430-bc77-4c06-9b9f-61620f06ab15)

So while I'm trying through Git...

**Comment by Necht** [comment]
> 4. Replace the `LocalizationPack.json` with your edited version.

I have to do it in the mod folder, what is in the game files?

**Comment by Necht** [comment]
will it work out that way?

[edited translation into Russian.txt](https://github.com/JohN100x1/IsekaiMod/files/11968434/edited.translation.into.Russian.txt)

**Comment by Necht** [comment]
> The settings menu doesn't use localized strings. It's hardcoded. The mechanism to change switch between localization in the game doesn't apply to the mod settings menu.

The new version of the Toy Box has a separate bar for switching the language in the settings menu. I haven't tried it, but maybe you can do something similar?

![image](https://github.com/JohN100x1/IsekaiMod/assets/128060492/3866df45-a7ec-4680-823e-b92235338a47)

![image](https://github.com/JohN100x1/IsekaiMod/assets/128060492/21cd8cb2-c304-4522-bf34-ea66d12c95d2)

**Comment by JohN100x1** [comment]
Ok I was able to build using your translation. There was some minor formatting issues, but otherwise it appears to be working.
Here's a test build
[IsekaiMod-5-3-4-a.zip](https://github.com/JohN100x1/IsekaiMod/files/11985037/IsekaiMod-5-3-4-a.zip)

**Comment by Necht** [comment]
Can you please check the Evil Legacy?

Everything is correct in the localization files, but in the game itself, the description of the evil legacy is replaced by the description of the Genius Legacy.

![image](https://github.com/JohN100x1/IsekaiMod/assets/128060492/78540da3-ed15-43b3-ad0d-93d2b20801c1)
![image](https://github.com/JohN100x1/IsekaiMod/assets/128060492/d1668558-fd41-4189-87e0-755e8bca4723)

Perhaps in the same way in English.

**Comment by Necht** [comment]
missing localization strings for kinetic knight

![image](https://github.com/JohN100x1/IsekaiMod/assets/128060492/ff360a8f-4515-4fb4-877d-ccf0197f0c43)

**Comment by Necht** [comment]
The translation is completely ready, only what I wrote earlier remains.

[LocalizationPack.zip](https://github.com/JohN100x1/IsekaiMod/files/11990696/LocalizationPack.zip)
