### ISSUE TITLE
Quit Game will cause Haggler invalid

### ISSUE THREAD

**Issue by a234106261** [JohN100x1/IsekaiMod#179]
**Describe the bug**
After quit the game, Haggler will not work. Once remove and add Haggler, all Haggler(>=2) will work again

**To Reproduce**
1. choose the Haggler myth feat
2. check the price of the vendor
3. quit the game and restart
4. check the price
5. remove and add Haggler of any chara
6. check the price

**Expected behavior**
Haggler should work after restart game

**Comment by a234106261** [comment]
Besides, IsekaiMod will cause the shifter ability bar got multiple shifterClaws icon when myth level up

**Comment by JohN100x1** [comment]
I could not replicate the multiple claw icon issue. Which shifter legacy did you choose?

**Comment by a234106261** [comment]
> I could not replicate the multiple claw icon issue. Which shifter legacy did you choose?

Ulbrig's default one.
I can reproduce the bug quickly as follows:
1. start a new save in DLC1, respec Ulbrig
2. level up Ulbrig to lv9 or higher
3. myth level up Ulbrig
4. then you can see the three or more shifter claws icon in the ability bar

**Comment by JohN100x1** [comment]
Should be fixed in 5.3.4
