### ISSUE TITLE
Localization into Russian

### ISSUE THREAD

**Issue by Necht** [JohN100x1/IsekaiMod#182]
The translation is completely ready, only what I wrote earlier remains.

[LocalizationPack.zip](https://github.com/JohN100x1/IsekaiMod/files/11990696/LocalizationPack.zip)

_Originally posted by @Necht in https://github.com/JohN100x1/IsekaiMod/issues/178#issuecomment-1627242296_

**Comment by Necht** [comment]
You didn't update the localization file for version 5.3.4 to the last one that I did.

**Comment by JohN100x1** [comment]
> You didn't update the localization file for version 5.3.4 to the last one that I did.
> 
> Apparently, I expressed myself incorrectly because of what this misunderstanding came about. This zip file is the final one at the moment. Without taking into account the shortcomings that I wrote about earlier in another topic.

OK I will update the localisation as soon as I arrive home.

**Comment by Necht** [comment]
Thanks!
