### ISSUE TITLE
I tried to adjust the Chinese translation

### ISSUE THREAD

**Issue by komoechan** [JohN100x1/IsekaiMod#192]
The Chinese translation has too many problem so I adjust it.

I‘m not a programmer, and this is my first time to use GitHub to change other people's project, so if I do something wrong, you can also get the Localization file here.

[LocalizationPack.zip](https://github.com/JohN100x1/IsekaiMod/files/12444884/LocalizationPack.zip)

**Comment by JohN100x1** [comment]
Thank you! I'll update the mod now.
